# Generated by Django 4.2.23 on 2025-07-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileconversion',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
