# Generated by Django 4.2.23 on 2025-07-18 21:36

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_converter', '0005_alter_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
