services:
  - type: web
    name: audio-converter-web
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: gunicorn audio_converter.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
    plan: free

  - type: worker
    name: audio-converter-celery
    env: python
    region: oregon
    startCommand: celery -A audio_converter worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
    plan: free